version: '3.8'
services:
    mysql:
        image: mysql:5.7
        container_name: docker_srv_mysql
        restart: "no"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db/bdd:/var/lib/mysql
            - ./docker/db/dump/name_dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: "dbtest"
            MYSQL_DATABASE: "dbtest"
            MYSQL_USER: "dbtest"
            MYSQL_PASSWORD: "dbtest"
        networks:
            dev:

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: docker_srv_phpmyadmin
        restart: "no"
        environment:
          PMA_HOST: "mysql"
          MYSQL_ROOT_PASSWORD: "dbtest"
          UPLOAD_LIMIT: "5000M"
        ports:
            - "8181:80"
        links:
            - mysql
        networks:
            dev:
    php:
        build: docker/php
        extra_hosts:
            - host.docker.internal:host-gateway
        expose:
            - "9003"
        container_name: docker_srv_apache_php
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
          - ./:/var/www
        restart: "no"
        networks:
            dev:
                ipv4_address: 192.152.0.0

networks:
    dev: